# Generated by Django 5.2.1 on 2025-06-03 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_car_latitude_car_longitude_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='title',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('price_update', 'Price updated'), ('favorite', 'Marked as favorite'), ('new_car', 'New car added')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
    ]
