name: arac_alim_uygulamasi
description: "Car listing & purchase app — UI branch"
publish_to: 'none' # private package

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_local_notifications: ^9.7.0
  connectivity_plus: ^5.0.2
  battery_plus: ^4.0.2
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0

  # Core icon pack
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2

  # State management
  flutter_riverpod: ^2.0.0

  # SVG desteği
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Wireframe varlıklarınız
  assets:
    - design/wireframes/
