name: flutter_background_features
description: A Flutter project demonstrating background task and broadcast receiver.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_local_notifications: ^9.7.0
  connectivity_plus: ^5.0.2
  battery_plus: ^4.0.2
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
