name: arac_alim_uygulamasi
description: "Car listing & purchase app — UI branch"
publish_to: 'none' # private package

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # *** STATE / DI ***
  flutter_riverpod: ^2.6.1

  # *** NETWORKING ***
  dio: ^5.8.0+1                 # HTTP-istemcisi
  flutter_secure_storage: ^9.2.4  # JWT saklamak için
  intl: ^0.19.0               # tarih–saat biçimleme, para birimi

  # *** LOCAL DB & CACHE (ops.) ***
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

  # Aşağısını ekleyin:
  drift: ^2.26.1
  drift_flutter: ^0.2.4

  workmanager: ^0.6.0
  flutter_local_notifications: ^19.2.1
  connectivity_plus: 6.1.4

  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  geocoding: ^4.0.0

  flutter_localizations:
    sdk: flutter

  battery_plus: ^6.2.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_lints: ^3.0.1
  build_runner: 2.4.15
  json_serializable: ^6.9.5
  drift_dev: ^2.26.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env