name: arac_alim_uygulamasi
description: "Car listing & purchase app — UI branch"
publish_to: 'none' # private package

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core icon pack
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.0.0

  # SVG desteği
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Wireframe varlıklarınız
  assets:
    - design/wireframes/
